CREATE TABLE PASSWORDS (
	PID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(256),
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	DATE_ADDED DATETIME NOT NULL,
	DATE_UPDATED DATETIME NOT NULL,
	ACTIVE INT NOT NULL,
	PRIMARY KEY (PID)
) ENGINE=INNODB;

CREATE TABLE GROUPS (
	GID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(256),
	ACTIVE INT NOT NULL,
	PRIMARY KEY (GID)
) ENGINE=INNODB;

CREATE TABLE PASSWORD_GROUPS (
	GID INT NOT NULL,
	PID INT NOT NULL,
	DATE_ADDED DATETIME NOT NULL,
	PRIMARY KEY (GID, PID),
	FOREIGN KEY (GID) REFERENCES GROUPS(GID),
	FOREIGN KEY (PID) REFERENCES PASSWORDS(PID)
) ENGINE=INNODB;

CREATE TABLE USERS (
	UID VARCHAR(8) NOT NULL,
	DATE_ADDED DATETIME NOT NULL,
	ACTIVE INT NOT NULL,
	PRIMARY KEY (UID)
) ENGINE=INNODB;

CREATE TABLE USER_GROUPS (
	UID VARCHAR(8) NOT NULL,
	GID INT NOT NULL,
	DATE_ADDED DATETIME NOT NULL,
	ROLE CHAR(1) NOT NULL,
	PRIMARY KEY (UID, GID),
	FOREIGN KEY (UID) REFERENCES USERS(UID),
	FOREIGN KEY (GID) REFERENCES GROUPS(GID)
) ENGINE=INNODB;

CREATE TABLE USER_PASSWORDS (
	UID VARCHAR(8) NOT NULL,
	PID INT NOT NULL,
	DATE_ADDED DATETIME NOT NULL,
	PRIMARY KEY (UID, PID),
	FOREIGN KEY (UID) REFERENCES USERS(UID),
	FOREIGN KEY (PID) REFERENCES PASSWORDS(PID)
) ENGINE=INNODB;

CREATE TABLE LOGIN_HISTORY (
	UID VARCHAR(8) NOT NULL,
	IP_ADDR VARCHAR(15) NOT NULL,
	DATETIME DATETIME NOT NULL,
	FOREIGN KEY (UID) REFERENCES USERS(UID)
) ENGINE=INNODB;

CREATE TABLE PASSWORD_CHANGE_HISTORY (
	UID VARCHAR(8) NOT NULL,
	PID INT NOT NULL,
	PREVIOUS_VALUE VARCHAR(32) NOT NULL,
	DATETIME DATETIME NOT NULL,
	FOREIGN KEY (UID) REFERENCES USERS(UID),
	FOREIGN KEY (PID) REFERENCES PASSWORDS(PID)
) ENGINE=INNODB;